// <auto-generated />
using System;
using JustRentItAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JustRentItAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228145918_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JustRentItAPI.Models.Entities.AgeGroup", b =>
                {
                    b.Property<int>("AgeGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgeGroupID"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameHebrew")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AgeGroupID");

                    b.ToTable("AgeGroups");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityID"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameHebrew")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Color", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorID"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameHebrew")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ColorID");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Dress", b =>
                {
                    b.Property<int>("DressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DressID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("SaleType")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("DressID");

                    b.HasIndex("UserID");

                    b.ToTable("Dresses");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressAgeGroup", b =>
                {
                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<int>("AgeGroupID")
                        .HasColumnType("integer");

                    b.HasKey("DressID", "AgeGroupID");

                    b.HasIndex("AgeGroupID");

                    b.ToTable("DressAgeGroups");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressCity", b =>
                {
                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<int>("CityID")
                        .HasColumnType("integer");

                    b.HasKey("DressID", "CityID");

                    b.HasIndex("CityID");

                    b.ToTable("DressCities");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressColor", b =>
                {
                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<int>("ColorID")
                        .HasColumnType("integer");

                    b.HasKey("DressID", "ColorID");

                    b.HasIndex("ColorID");

                    b.ToTable("DressColors");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressEventType", b =>
                {
                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<int>("EventTypeID")
                        .HasColumnType("integer");

                    b.HasKey("DressID", "EventTypeID");

                    b.HasIndex("EventTypeID");

                    b.ToTable("DressEventTypes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressImage", b =>
                {
                    b.Property<int>("DressImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DressImageID"));

                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("DressImageID");

                    b.HasIndex("DressID");

                    b.ToTable("DressImages");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressSize", b =>
                {
                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<int>("SizeID")
                        .HasColumnType("integer");

                    b.HasKey("DressID", "SizeID");

                    b.HasIndex("SizeID");

                    b.ToTable("DressSizes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.EventType", b =>
                {
                    b.Property<int>("EventTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventTypeID"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameHebrew")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EventTypeID");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteID"));

                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("FavoriteID");

                    b.HasIndex("DressID");

                    b.HasIndex("UserID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Interest", b =>
                {
                    b.Property<int>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterestID"));

                    b.Property<int>("DressID")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OwnerComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OwnerMailCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("UserMailCount")
                        .HasColumnType("integer");

                    b.HasKey("InterestID");

                    b.HasIndex("DressID");

                    b.HasIndex("UserID");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.MonthlySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MonthlySummaries");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Size", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SizeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("SizeID");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Dress", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.User", "User")
                        .WithMany("Dresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressAgeGroup", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.AgeGroup", "AgeGroup")
                        .WithMany("DressAgeGroups")
                        .HasForeignKey("AgeGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("AgeGroups")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeGroup");

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressCity", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.City", "City")
                        .WithMany("DressCities")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("Cities")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressColor", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.Color", "Color")
                        .WithMany("DressColors")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("Colors")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressEventType", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("EventTypes")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.EventType", "EventType")
                        .WithMany("DressEventTypes")
                        .HasForeignKey("EventTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dress");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressImage", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("Images")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.DressSize", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("Sizes")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.Size", "Size")
                        .WithMany("DressSizes")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dress");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Favorite", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("Favorites")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Interest", b =>
                {
                    b.HasOne("JustRentItAPI.Models.Entities.Dress", "Dress")
                        .WithMany("Interests")
                        .HasForeignKey("DressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JustRentItAPI.Models.Entities.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.AgeGroup", b =>
                {
                    b.Navigation("DressAgeGroups");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.City", b =>
                {
                    b.Navigation("DressCities");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Color", b =>
                {
                    b.Navigation("DressColors");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Dress", b =>
                {
                    b.Navigation("AgeGroups");

                    b.Navigation("Cities");

                    b.Navigation("Colors");

                    b.Navigation("EventTypes");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Interests");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.EventType", b =>
                {
                    b.Navigation("DressEventTypes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.Size", b =>
                {
                    b.Navigation("DressSizes");
                });

            modelBuilder.Entity("JustRentItAPI.Models.Entities.User", b =>
                {
                    b.Navigation("Dresses");

                    b.Navigation("Favorites");

                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
